# Ansible playbook for deploying a Flask app
---
- hosts: webservers
  become: yes
  tasks:
  - name: installing pip3
    apt: name=python3-pip state=latest
  - name: installing flask module
    pip: name=flask state=latest
  - name: run flask app
    shell: |
      nohup python3 /etc/ansible/application.py > log.txt 2>&1 &
